### PR TITLE
Remove compilation error when -Wshadow flag is set

### PR DESCRIPTION
**Pull request by stainleebakhla**
Hi,

This PR fixes compilation error which is caused when -Wshadow flag is set.

Thanks
Stainlee

### CODE REVIEW

**Comment by Tessil** [comment]
Hi,

Thank you for your contribution.

Would it be possible to rename `count_local` to `count_` as done for [hopscotch-map](https://github.com/Tessil/hopscotch-map/commit/90b31396cd908a42d0a67372c691867b01547fb9)?

Thanks,
Thibaut

**Comment by stainleebakhla** [comment]
Yes. Definitely.

Will send a PR soon.

**Comment by Tessil** [comment]
Thank you, I merged the changes.

**Comment by halx99** [comment]
Use `n` instead may be better

**Pull request merged**
